[package]
name = "rust-spice-derive"
version = "1.0.1"
authors = ["Grégoire Henry <greg.henry@mail.com>"]
edition = "2021"
rust-version = "1.70"
description = "Procedural macros for rust-spice, an idiomatic Rust interface to the NASA/NAIF Spice toolkit."
license = "Apache-2.0"
repository = "https://github.com/GregoireHENRY/rust-spice"
keywords = ["space", "spice", "nasa", "naif", "kernels"]
categories = ["algorithms", "api-bindings", "science"]

[lib]
name = "spice_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "3.0", features = ["full", "parsing", "printing", "clone-impls", "proc-macro"] }
