"""Write `rust-spice/src/unlinked.rs` from the bindings `cspice-sys` generates.

The `unlinked` feature declares the CSPICE API without asking the machine for a copy of the
toolkit, which is how the crate documents itself on docs.rs: the build script of `cspice-sys`
cannot run there. Nothing is linked, so the result can be documented and type checked, never run.

Run it after a `cargo build`, which is what puts the generated bindings under `target/`.
"""
import glob, os, pathlib, re, subprocess, sys

HEADER = '''/*!
The CSPICE API, declared rather than generated.

This is what the `unlinked` feature puts behind [`crate::c`] in place of the bindings `cspice-sys`
writes from the headers of the toolkit installed on the machine. It exists because docs.rs cannot
run that build script, and it is what lets the crate document itself there.

Nothing here is linked against anything, so a program built this way will not resolve a single one
of these symbols. It is enough to document the crate and to type check it, and no more.

Generated by `tools/bindings.py` from rust-bindgen {version} over CSPICE {toolkit}; do not edit.
*/

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]
#![allow(clippy::all)]

'''


def strip_tests(text):
    """Drop the layout assertions: this copy is declarations, and the real bindings keep them."""
    out, lines, index = [], text.splitlines(keepends=True), 0
    while index < len(lines):
        if lines[index].startswith('#[test]'):
            index += 1
            while index < len(lines) and not lines[index].startswith('}'):
                index += 1
            index += 1
            while index < len(lines) and lines[index].strip() == '':
                index += 1
            continue
        out.append(lines[index])
        index += 1
    return ''.join(out)


def main():
    found = sorted(glob.glob('target/*/build/cspice-sys-*/out/bindgen.rs'), key=os.path.getmtime)
    if not found:
        sys.exit('no generated bindings under target/; run `cargo build` first')
    text = pathlib.Path(found[-1]).read_text()
    version = re.search(r'rust-bindgen ([\d.]+)', text)
    toolkit = os.environ.get('CSPICE_VERSION', 'N0067')
    body = strip_tests(text)
    body = re.sub(r'^/\* automatically generated[^\n]*\n\n?', '', body)
    out = pathlib.Path('rust-spice/src/unlinked.rs')
    out.write_text(HEADER.format(version=version.group(1) if version else 'unknown',
                                 toolkit=toolkit) + body)
    # `cargo fmt` covers the file like any other, so write it the way rustfmt wants it in the first
    # place: otherwise formatting it would look like the copy had drifted.
    subprocess.run(['rustfmt', '--edition', '2021', str(out)], check=True)
    print(f'{out}: {len(out.read_text().splitlines())} lines, {out.stat().st_size // 1024} KiB')


main()
